* Encoding: UTF-8.
DATASET CLOSE all.
GET FILE='Data\moz_hhq_raw.sav'.

FREQUENCIES L2A$01 to L2A$05 L2A$20 to L2A$22.

RECODE L2A$20
    (0 = 2)
    (1 THRU 5 = 1)
    INTO L2A_20.

FREQUENCIES L2A_20.

VARIABLE LABELS
  L2A$01 'Cama'
/ L2A$02 'Mesa'
/ L2A$03 'Bicicleta'
/ L2A$04 'Motocicleta'
/ L2A$05 'VeÃ­culo'
/ L2A_20 'LÃ¡mpada incandescente'
.


MRSETS
  /MDGROUP NAME=$assets LABEL='Assets'
   CATEGORYLABELS=VARLABELS VARIABLES=L2A$01 to L2A$05 L2A_20 VALUE=1
  /DISPLAY NAME=[$Assets].


CTABLES
  /VLABELS VARIABLES=AA1 $assets DISPLAY=LABEL
  /TABLE AA1 [COUNT F40.0] BY $assets
  /SLABELS VISIBLE=NO
  /CATEGORIES VARIABLES=AA1 ORDER=A KEY=VALUE EMPTY=EXCLUDE TOTAL=YES POSITION=BEFORE
  /CATEGORIES VARIABLES=$assets  EMPTY=INCLUDE
  /CRITERIA CILEVEL=95.

DATASET CLOSE all.
GET FILE='Data\TZHHLEVEL_4.sav'.

CTABLES
  /VLABELS VARIABLES=Region HHOccupStatus_gr1 to HHOccupStatus_gr5 DISPLAY=LABEL
  /TABLE Region [COUNT F40.0] BY HHOccupStatus_gr1 + HHOccupStatus_gr2 + HHOccupStatus_gr3 + HHOccupStatus_gr4 + HHOccupStatus_gr5
  /SLABELS VISIBLE=NO
  /CATEGORIES VARIABLES=Region ORDER=A KEY=VALUE EMPTY=EXCLUDE TOTAL=YES POSITION=BEFORE
  /CATEGORIES VARIABLES=$HHOccupStatus  EMPTY=INCLUDE
 .

MRSETS
  /MDGROUP NAME=$HHOccupStatus LABEL='Occupation status'
   CATEGORYLABELS=VARLABELS VARIABLES=HHOccupStatus_gr1 to HHOccupStatus_gr5 VALUE=1
  /DISPLAY NAME=[$HHOccupStatus].

CTABLES
  /VLABELS VARIABLES=Region $HHOccupStatus HHOccupStatus_gr1 to HHOccupStatus_gr5 DISPLAY=LABEL
  /TABLE Region [rowpct.COUNT F40.0] BY $HHOccupStatus + HHOccupStatus_gr1 + HHOccupStatus_gr2 + HHOccupStatus_gr3 + HHOccupStatus_gr4 + HHOccupStatus_gr5
  /SLABELS VISIBLE=NO
  /CATEGORIES VARIABLES=Region ORDER=A KEY=VALUE EMPTY=EXCLUDE TOTAL=YES POSITION=BEFORE
  /CATEGORIES VARIABLES=$HHOccupStatus  EMPTY=INCLUDE
 .

CTABLES
  /VLABELS VARIABLES=Region $HHOccupStatus DISPLAY=NONE
  /TABLE Region  BY $HHOccupStatus [rowpct.COUNT F40.0]
  /SLABELS VISIBLE=NO
  /CATEGORIES VARIABLES=Region ORDER=A KEY=VALUE EMPTY=EXCLUDE TOTAL=YES POSITION=BEFORE
  /CATEGORIES VARIABLES=$HHOccupStatus  EMPTY=INCLUDE
 .



